name: Build Visual Studio solution
description: Builds a solution using the Microsoft Build engine
branding:
  icon: activity
  color: blue
inputs:
  solution-file:
    description: The path of the MSBuild solution file to build
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore Solution Packages
      run: nuget restore "${{ inputs.solution-file }}"
    - name: Build Solution
      run: msbuild "${{ inputs.solution-file }}" -m
